export default [
  {
    id: 1,
    batchId: 2,
    subjectId: 1,
    studentId: 1,
    Date: "06/28/2022",
    isPresent: true,
  },
  {
    id: 2,
    batchId: 2,
    subjectId: 2,
    studentId: 1,
    Date: "06/28/2022",
    isPresent: true,
  },
  {
    id: 10,
    batchId: 2,
    subjectId: 2,
    studentId: 2,
    Date: "06/28/2022",
    isPresent: true,
  },
  {
    id: 3,
    batchId: 2,
    subjectId: 3,
    studentId: 1,
    Date: "06/28/2022",
    isPresent: true,
  },
  {
    id: 4,
    batchId: 2,
    subjectId: 4,
    studentId: 1,
    Date: "06/28/2022",
    isPresent: true,
  },
  {
    id: 5,
    batchId: 2,
    subjectId: 5,
    studentId: 1,
    Date: "06/28/2022",
    isPresent: true,
  },
  {
    id: 6,
    batchId: 2,
    subjectId: 1,
    studentId: 2,
    Date: "06/28/2022",
    isPresent: true,
  },
  {
    id: 7,
    batchId: 2,
    subjectId: 2,
    studentId: 2,
    Date: "06/28/2022",
    isPresent: true,
  },
  {
    id: 8,
    batchId: 2,
    subjectId: 3,
    studentId: 2,
    Date: null,
    isPresent: null,
  },
  {
    id: 9,
    batchId: 2,
    subjectId: 4,
    studentId: 2,
    Date: null,
    isPresent: null,
  },
  {
    id: 10,
    batchId: 2,
    subjectId: 5,
    studentId: 2,
    Date: null,
    isPresent: null,
  },
];
